spring:
  cloud:
    stream:
      bindings:
        orders_supplier-out-0:
          contentType: application/*+avro
          destination: ride-requests
      schemaRegistryClient:
        endpoint: http://localhost:8081

server.port: 9009
