server.port: 8080

spring.cloud.stream:
  function:
    definition: process_users;

spring.cloud.stream.bindings.process_users-in-0:
  destination: users.users

spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    schema.registry.url: http://localhost:8081
    commit.interval.ms: 1000

spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1800000
      minimumIdle: 5
      maximumPoolSize: 20
      poolName: SpringBootJPAHikariCP
      schema: users


  jpa:
    properties:
      hibernate:
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
