server.port: 8090

spring.cloud.stream:
  kafka:
    binder:
      transaction:
        transaction-id-prefix: user-
        producer:
          configuration:
            retries: 1
            acks: all
  function:
    definition: process_ride_requests;

spring.cloud.stream.bindings.process_ride_requests-in-0:
  destination: users
spring.cloud.stream.bindings.process_ride_requests-out-0:
  destination: users-out






spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    schema.registry.url: http://localhost:8081
    commit.interval.ms: 1000

spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
